using System.Collections.Generic;
using UnityEngine;

namespace DeadCells.Audio
{
    [System.Serializable]
    public class SoundEvent
    {
        public string id;
        public AudioClip[] clips = new AudioClip[0];
        [Range(0f, 1.5f)] public float volume = 1f;
        public Vector2 pitch = new Vector2(0.95f, 1.05f);
        [Tooltip("Minimum seconds between two plays of this event.")]
        public float cooldown = 0.03f;
        [Tooltip("Maximum simultaneous voices of this event.")]
        public int voices = 4;
        [Tooltip("Panned and attenuated by its distance from the camera.")]
        public bool spatial = true;
    }

    [System.Serializable]
    public class MusicTrack
    {
        public string id;
        public AudioClip clip;
        [Range(0f, 1.5f)] public float volume = 0.75f;
        public bool loop = true;
    }

    /// <summary>
    /// Every sound the game can play, generated by Tools/Audio/make_audio.py and
    /// collected by the content builder into Resources/SoundBank.
    /// </summary>
    public class SoundBank : ScriptableObject
    {
        public List<SoundEvent> sfx = new List<SoundEvent>();
        public List<MusicTrack> music = new List<MusicTrack>();
        public List<MusicTrack> ambience = new List<MusicTrack>();
    }
}
